name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  web:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    name: Frontend Deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload all files to S3
        run: aws s3 sync /web s3://app47captchademo/ --delete --exclude "*.DS_Store"
